name: Approve Command Dispatch

on:
  repository_dispatch:
    types: [ approve-command ]
  workflow_dispatch:

jobs:
  approve-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2.4.2

      - name: Get Issue Body
        id: get-issue-body
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: |
          BODY=$(echo "$PAYLOAD_CONTEXT" | jq .github.payload.issue.body)
          echo "::set-output name=body::$BODY"

      - name: parse issue
        uses: GrantBirki/issue-template-parser@main
        id: issue-parser
        with:
          body: ${{ steps.get-issue-body.outputs.body }}

      - name: echo body
        run: echo $ISSUE_BODY
        env:
          ISSUE_BODY: ${{ steps.issue-parser.outputs.json }}

      - name: check if repo exists
        env:
          OWNER: ersilia-os
          JSON: ${{ steps.issue-parser.outputs.json }}
        run: |

          echo $JSON | jq .'ersilia_id'

          REPO_NAME=$(echo $JSON | jq .'ersilia_id')

          URL="https://api.github.com/repos/${OWNER}/${REPO_NAME}"

          curl -s $URL > /dev/null

          if [ $? -eq 0 ]; then
            echo "Repo ${OWNER}/${REPO} already exists ❌"
            exit 1
          fi

          echo "Repo ${OWNER}/${REPO} is available ✅"
