name: Approve Command Dispatch

on:
  repository_dispatch:
    types: [ approve-command ]

jobs:
  approve-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2.4.2

      - name: Get Issue Body
        id: get-issue-body
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: |
          BODY=$(echo "$PAYLOAD_CONTEXT" | jq .github.payload.issue.body)
          echo "::set-output name=body::$BODY"

      - name: Issue Template Parser
        id: issue-parser
        uses: GrantBirki/issue-template-parser@v3.0.2
        with:
          issue-body: ${{ steps.get-issue-body.outputs.body }}
          template-path: .github/ISSUE_TEMPLATE/model_request.yml

      - run: echo "$ISSUE_CONTEXT"
        env:
          ISSUE_CONTEXT: ${{ steps.issue-parser.outputs.jsonString }}
