name: Approve Command Dispatch

on:
  repository_dispatch:
    types: [ approve-command ]

jobs:
  approve-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # pin@v2.4.2

      - name: Approve Command Dispatch
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      - name: echo github event path
        run: echo $GITHUB_EVENT_PATH

      - name: GitHub Issue Parser
        uses: stefanbuck/github-issue-parser@f80b14f78892a66d7a35bba44f0a7d63bee03602 # pin@v2.0.4
        with:
          template-path: .github/ISSUE_TEMPLATE/model_request.yml

      - run: echo "$ISSUE_CONTEXT"
        env:
          ISSUE_CONTEXT: ${{ steps.issue-parser.outputs.jsonString }}
