name: "command demo"

# the workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [ created ]

# permissions needed for reacting to IssueOps commands on issues and PRs
permissions:
  pull-requests: write
  issues: write
  checks: read

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      # execute IssueOps command logic, hooray!
      # this will be used to "gate" all future steps below
      - uses: github/command@fork-safety
        id: ping
        with:
          command: ".ping"
          allow_forks: true
          fork_review_bypass: false

      # run your custom logic for your project here - example seen below

      # conditionally run some logic here
      - name: ping command
        if: ${{ steps.ping.outputs.continue == 'true' }}
        run: echo 'Got comment in PR \#${{ steps.ping.outputs.issue_number }} with params ${{ steps.ping.outputs.params }} - base_ref ${{ steps.ping.outputs.base_ref }}'
        
