name: "command demo"

# the workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [ created ]

# permissions needed for reacting to IssueOps commands on issues and PRs
permissions:
  pull-requests: write
  issues: write
  checks: read

jobs:
  demo:
    if: ${{ contains(fromJSON('["OWNER", "MEMBER"]'), github.event.comment.author_association) }}
    runs-on: ubuntu-latest
    steps:
      # execute IssueOps command logic, hooray!
      # this will be used to "gate" all future steps below
      - uses: github/command@main
        id: ping
        with:
          command: ".ping"

      # run your custom logic for your project here - example seen below

      # conditionally run some logic here
      - name: ping command
        if: ${{ steps.ping.outputs.continue == 'true' }}
        env:
          ISSUE_NUMBER: ${{ steps.ping.outputs.issue_number }}
          PARAMS: ${{ steps.ping.outputs.params }}
          BASE_REF: ${{ steps.ping.outputs.base_ref }}
        run: printf 'Got comment in PR \#%s with params %s - base_ref %s\n' "$ISSUE_NUMBER" "$PARAMS" "$BASE_REF"

