name: json and yaml check 
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  json-yaml-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0

      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@main
        with:
          comment: "true"
          json_exclude_regex: ".*test2.json"
          yaml_exclude_regex: ".*test2.yml"
          # exclude_file: test/config/exclude.txt
