name: pr-status

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, review_request_removed, labeled, unlabeled]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  contents: read
  checks: read
  pull-requests: write # read works if you are not using label add/delete logic

jobs:
  pr-status:
    runs-on: ubuntu-latest

    steps:
      - uses: grantbirki/pr-status@copilot/fix-39
        id: pr-status
        with:
          pass_labels: ready-for-deployment
          evaluations: approved
      
      - name: outputs
        run: |
          echo "approved: ${{ steps.pr-status.outputs.approved }}"
          echo "total approvals ${{ steps.pr-status.outputs.total_approvals }}"
