name: pr-status

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  pr-status:
    runs-on: ubuntu-latest

    steps:
      - uses: grantbirki/pr-status@main
        id: pr-status
      
      - name: outputs
        run: |
          echo "approved: ${{ steps.pr-status.outputs.approved }}"
