# name: test1

# on:
#   pull_request:

# permissions:
#   contents: read

# jobs:
#   test1:
#     name: test1
#     runs-on: ubuntu-latest

#     steps:
#       - name: it will pass
#         run: echo "success"
