name: testing-the-auditor

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: auditor-action
        uses: GrantBirki/auditor-action@v0.0.1
        with:
          config: config/auditor.yml
