name: Unlock On Merge

on:
  pull_request:
    types: [closed]

permissions:
  deployments: read
  contents: write

jobs:
  unlock-on-merge:
    runs-on: ubuntu-latest

    steps:
      - name: unlock on merge
        uses: grantbirki/branch-deploy@a135df25401c9513be3882f886f74e1d4d0729be
        id: unlock-on-merge
        with:
          unlock_on_merge_mode: "true" # <-- indicates that this is the "Unlock on Merge Mode" workflow
          environment_targets: production,development,staging,super production,mellow staging
