name: view-event

on:
  push:
  pull_request:
  issue_comment:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: view github event
        run: cat $GITHUB_EVENT_PATH | jq . 
